### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by GR90** [Xyene/sphere2cube#7]
pip install sphere2cube             win10,python3.4 3.7  
![1551945113](https://user-images.githubusercontent.com/19780276/53940575-fba90e80-40f0-11e9-8480-29ecaa0ed252.jpg)

**Comment by Toshiwoz** [comment]
same problem here.

**Comment by Toshiwoz** [comment]
I figured out how to do the same using povray. So no hurry anymore.

**Comment by sunguwei** [comment]
same problem here, too

**Comment by Xyene** [comment]
This sounds like the package was incorrectly marked as Python 3-compatible, which it isn't due to `ez_setup` being Python 2-only. If you use a Python 2 install's `pip`, or do something like:

```sh
$ git clone https://github.com/Xyene/sphere2cube
$ cd sphere2cube
$ python setup.py develop
```

...that should also work, providing that `python` is a Python 2 version.

**Comment by sunguwei** [comment]
Got it, thanks very much!!!

**Comment by mangorism** [comment]
I can install sphere2cube with python2 ...
but cann't install bpy(blender python) in python2..

I can install bpy in python3
but cann't install sphere2cube in python3....

how can I install both of them in windows...?

**Comment by Xyene** [comment]
Over a year later, I've updated this project to Python 3 :)

Never expected anyone to actually use this, and I haven't done graphics stuff in years, but felt it unfair to leave people hanging _forever_.
