### ISSUE TITLE
output file is blank

### ISSUE THREAD

**Issue by ihao** [Xyene/sphere2cube#9]
os: macos 10.15.2
python: 2.7.16
blender: 2.81a
sphere2cube: 0.1.8

when i use `sphere2cube main.jpg -fJPEG` to generate cube pics, six pics is created with name:face_1_1024.jpg, face_2_1024.jpg...
at the same fold with "main.jpg", 
but cube pics is blank with no resource in it!

i saw "projector.blend" was created four years ago, is that blend file not match 2.81a version in blender?

![main](https://user-images.githubusercontent.com/4046/71661078-0f141d00-2d88-11ea-81c7-1cd27b2a3186.jpg)
![face_1_1024](https://user-images.githubusercontent.com/4046/71661090-1804ee80-2d88-11ea-8286-97f54f0797b9.jpg)
![face_2_1024](https://user-images.githubusercontent.com/4046/71661091-1804ee80-2d88-11ea-8e02-00db31b47c2a.jpg)
![face_3_1024](https://user-images.githubusercontent.com/4046/71661092-1804ee80-2d88-11ea-8130-60bae4c049ca.jpg)
![face_4_1024](https://user-images.githubusercontent.com/4046/71661093-189d8500-2d88-11ea-8f90-dff934010936.jpg)
![face_5_1024](https://user-images.githubusercontent.com/4046/71661094-19361b80-2d88-11ea-8f6d-98a8d62a4881.jpg)
![face_6_1024](https://user-images.githubusercontent.com/4046/71661095-19361b80-2d88-11ea-94ac-08334492a597.jpg)

sorry for my poor english, just need help.

**Comment by Xyene** [comment]
I believe I have fixed this in the latest master, if you are still interested. The Blender file bundled in with this project was never compatible with Cycles, and the old renderer seems to have been removed in the 5 years since I first pushed it.
